[workspace]
members = [
    "examples/simple",
    "examples/extra-renders",
    "yarte",
    "yarte_codegen",
    "yarte_derive",
    "yarte_helpers",
    "yarte_hir",
    "yarte_html",
    "yarte_parser",
]
